// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel2_ConsoleApp2
{
    public partial class MLModel2
    {
        /// <summary>
        /// model input class for MLModel2.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(1)]
            [ColumnName(@"dur")]
            public float Dur { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"proto")]
            public string Proto { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"state")]
            public string State { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"spkts")]
            public float Spkts { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"dpkts")]
            public float Dpkts { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"sbytes")]
            public float Sbytes { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"dbytes")]
            public float Dbytes { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"rate")]
            public float Rate { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"sttl")]
            public float Sttl { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"dttl")]
            public float Dttl { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"sload")]
            public float Sload { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"dload")]
            public float Dload { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"sloss")]
            public float Sloss { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"dloss")]
            public float Dloss { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"sinpkt")]
            public float Sinpkt { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"dinpkt")]
            public float Dinpkt { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"sjit")]
            public float Sjit { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"djit")]
            public float Djit { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"swin")]
            public float Swin { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"stcpb")]
            public float Stcpb { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"dtcpb")]
            public float Dtcpb { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"dwin")]
            public float Dwin { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"tcprtt")]
            public float Tcprtt { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"synack")]
            public float Synack { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"ackdat")]
            public float Ackdat { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"smean")]
            public float Smean { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"dmean")]
            public float Dmean { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"trans_depth")]
            public float Trans_depth { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"response_body_len")]
            public float Response_body_len { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"ct_srv_src")]
            public float Ct_srv_src { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"ct_state_ttl")]
            public float Ct_state_ttl { get; set; }

            [LoadColumn(33)]
            [ColumnName(@"ct_dst_ltm")]
            public float Ct_dst_ltm { get; set; }

            [LoadColumn(34)]
            [ColumnName(@"ct_src_dport_ltm")]
            public float Ct_src_dport_ltm { get; set; }

            [LoadColumn(35)]
            [ColumnName(@"ct_dst_sport_ltm")]
            public float Ct_dst_sport_ltm { get; set; }

            [LoadColumn(36)]
            [ColumnName(@"ct_dst_src_ltm")]
            public float Ct_dst_src_ltm { get; set; }

            [LoadColumn(37)]
            [ColumnName(@"is_ftp_login")]
            public float Is_ftp_login { get; set; }

            [LoadColumn(38)]
            [ColumnName(@"ct_ftp_cmd")]
            public float Ct_ftp_cmd { get; set; }

            [LoadColumn(39)]
            [ColumnName(@"ct_flw_http_mthd")]
            public float Ct_flw_http_mthd { get; set; }

            [LoadColumn(40)]
            [ColumnName(@"ct_src_ltm")]
            public float Ct_src_ltm { get; set; }

            [LoadColumn(41)]
            [ColumnName(@"ct_srv_dst")]
            public float Ct_srv_dst { get; set; }

            [LoadColumn(42)]
            [ColumnName(@"is_sm_ips_ports")]
            public float Is_sm_ips_ports { get; set; }

            [LoadColumn(44)]
            [ColumnName(@"label")]
            public float Label { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel2.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"dur")]
            public float Dur { get; set; }

            [ColumnName(@"proto")]
            public float[] Proto { get; set; }

            [ColumnName(@"state")]
            public float[] State { get; set; }

            [ColumnName(@"spkts")]
            public float Spkts { get; set; }

            [ColumnName(@"dpkts")]
            public float Dpkts { get; set; }

            [ColumnName(@"sbytes")]
            public float Sbytes { get; set; }

            [ColumnName(@"dbytes")]
            public float Dbytes { get; set; }

            [ColumnName(@"rate")]
            public float Rate { get; set; }

            [ColumnName(@"sttl")]
            public float Sttl { get; set; }

            [ColumnName(@"dttl")]
            public float Dttl { get; set; }

            [ColumnName(@"sload")]
            public float Sload { get; set; }

            [ColumnName(@"dload")]
            public float Dload { get; set; }

            [ColumnName(@"sloss")]
            public float Sloss { get; set; }

            [ColumnName(@"dloss")]
            public float Dloss { get; set; }

            [ColumnName(@"sinpkt")]
            public float Sinpkt { get; set; }

            [ColumnName(@"dinpkt")]
            public float Dinpkt { get; set; }

            [ColumnName(@"sjit")]
            public float Sjit { get; set; }

            [ColumnName(@"djit")]
            public float Djit { get; set; }

            [ColumnName(@"swin")]
            public float Swin { get; set; }

            [ColumnName(@"stcpb")]
            public float Stcpb { get; set; }

            [ColumnName(@"dtcpb")]
            public float Dtcpb { get; set; }

            [ColumnName(@"dwin")]
            public float Dwin { get; set; }

            [ColumnName(@"tcprtt")]
            public float Tcprtt { get; set; }

            [ColumnName(@"synack")]
            public float Synack { get; set; }

            [ColumnName(@"ackdat")]
            public float Ackdat { get; set; }

            [ColumnName(@"smean")]
            public float Smean { get; set; }

            [ColumnName(@"dmean")]
            public float Dmean { get; set; }

            [ColumnName(@"trans_depth")]
            public float Trans_depth { get; set; }

            [ColumnName(@"response_body_len")]
            public float Response_body_len { get; set; }

            [ColumnName(@"ct_srv_src")]
            public float Ct_srv_src { get; set; }

            [ColumnName(@"ct_state_ttl")]
            public float Ct_state_ttl { get; set; }

            [ColumnName(@"ct_dst_ltm")]
            public float Ct_dst_ltm { get; set; }

            [ColumnName(@"ct_src_dport_ltm")]
            public float Ct_src_dport_ltm { get; set; }

            [ColumnName(@"ct_dst_sport_ltm")]
            public float Ct_dst_sport_ltm { get; set; }

            [ColumnName(@"ct_dst_src_ltm")]
            public float Ct_dst_src_ltm { get; set; }

            [ColumnName(@"is_ftp_login")]
            public float Is_ftp_login { get; set; }

            [ColumnName(@"ct_ftp_cmd")]
            public float Ct_ftp_cmd { get; set; }

            [ColumnName(@"ct_flw_http_mthd")]
            public float Ct_flw_http_mthd { get; set; }

            [ColumnName(@"ct_src_ltm")]
            public float Ct_src_ltm { get; set; }

            [ColumnName(@"ct_srv_dst")]
            public float Ct_srv_dst { get; set; }

            [ColumnName(@"is_sm_ips_ports")]
            public float Is_sm_ips_ports { get; set; }

            [ColumnName(@"label")]
            public uint Label { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel2.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("label");
            if (labelColumn == null)
            {
                throw new Exception("label column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<float>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
